Lucas.duarte
joaoarthurbm/arqsoft-blog pull request #76
Opened 2021-04-16 23:57 UTC by lucasvduarte

Adição do markdown da descrição da arquitetura do UnForm para a disciplina arquitetura de software

2021-04-16 23:59 UTC, lucasvduarte commented
Mini-projeto 1: Parte 1 - UnForm

2021-04-23 21:06 UTC, joaoarthurbm approved these changes, later dismissed
Ótimo. Vamos em frente.

2021-04-23 21:07 UTC, joaoarthurbm requested changes
Há repetição das seções.

2021-04-28 23:30 UTC, lucasvduarte commented
> Há repetição das seções.

retirada as seções que ainda não foram escritas

2021-04-30 21:08 UTC, lucasvduarte commented
Mini projeto 1, entrega do documento final.

2021-05-04 18:17 UTC, joaoarthurbm requested changes
Precisa melhorar bastante.

2021-05-04 18:17 UTC, joaoarthurbm commented on content/posts/un-form.md
> +Este documento descreve a arquitetura do [unForm](https://github.com/unform/unform).
Diagrama um pouco inapropriado. Não separa o que é externo do que é o sistema. Não diferencia visualmente partes do sistema e seus usuários. Input não é algo que deva estar no diagrama de contexto.

2021-05-04 18:17 UTC, joaoarthurbm commented on content/posts/un-form.md
> +## Containers
Onde está o diagrama de containers?

2021-05-04 18:17 UTC, joaoarthurbm commented on content/posts/un-form.md
> +![Diagrama de Máquina de Estados](vissao-informacao.png)
Em alguns momentos os retângulos são atividades, mas em outros são estados/substantivos.

2022-11-04 21:51 UTC, closed without merging