add LearnSystemVerilog
joaoarthurbm/arqsoft-blog pull request #79
Opened 2021-04-17 02:06 UTC by MatzCouz

Adicionando meu documento do projeto de Arquitetura de Software.

2021-04-23 19:24 UTC, joaoarthurbm requested changes
Oi, Matheus. Você precisa adicionar o cabeçalho para a página principal do blog poder construir um preview do seu post. Era só ter visto o exemplo que passei. Aqui vai de novo:

+++
title = "Exemplo de documento a ser produzido"
date = 2019-10-22
tags = []
categories = []
+++

***

2021-04-23 19:24 UTC, joaoarthurbm commented on content/posts/LearnSystemVerilog.md
> +# LearnSystemVerilog - Um simulador didático de SystemVerilog*Matheus Coutinho - UFCG****## O projeto consiste em uma aplicação Web que simula a execução de código em SystemVerilog em uma placa
Este não é o formato do arquivo md de exemplo. Tente seguir as instruções e o exemplo que passei.

2021-04-26 13:26 UTC, MatzCouz commented
Realizei as alterações!

2021-04-26 15:47 UTC, joaoarthurbm requested changes
O seu post ainda não está sendo formatado de maneira correta. Peço novamente que teste com o hugo em sua máquina antes de submeter.

2021-05-01 02:11 UTC, MatzCouz commented
Corrigi todos os erros, enviei o projeto com o resto da documentação, tudo corrigido! espero que dê certo.

2021-05-04 18:32 UTC, joaoarthurbm approved these changes
ok!

2021-05-04 18:32 UTC, joaoarthurbm commented on content/posts/learnsystemverilog.md
> +<img src="../learnSystemVerilog/contexto.png" alt="Diagrama de contexto" ></img>
acho que valeria a pena delimitar o que é o sistema do que é externo. deixar o sistema como uma coisa só. Não entendi o que são essas apis.

2021-05-04 18:32 UTC, merged